default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000
  

development:
  <<: *default
  database: tcc
test:
  <<: *default
  database: tcc

production:
  <<: *default
database: tcc